name: Build ImmortalWrt
on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc unzip zlib1g-dev file
    - name: Clone ImmortalWrt
      run: |
        git clone -b <branch> --single-branch --filter=blob:none https://github.com/immortalwrt/immortalwrt
        cd immortalwrt
    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Configure build
      run: make menuconfig
    - name: Build firmware
      run: make
